# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20161229_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationshiptype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='relationshiptype',
            name='is_symmetric',
            field=models.BooleanField(default=False),
        ),
    ]
