# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 18:31
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
        call_command('loaddata', 'initial_relationshiptypes', app_label='people')


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_add_unique_add_symmetric'),
    ]
    operations = [
        migrations.RunPython(load_fixture, reverse_code=migrations.RunPython.noop),
    ]
