# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_initial_relationshiptypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['authorized_name'], 'verbose_name_plural': 'People'},
        ),
        migrations.AddField(
            model_name='person',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
