sudo: required
language: python

python:
  - "3.5"

env:
  global:
  - SOLR_VERSION=6.6.3
  - SOLR_CORE=test-winthrop
cache:
  directories:
  - downloads

services:
  - mysql

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install codecov
  - cp ci/testsettings.py winthrop/local_settings.py
  - python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> winthrop/local_settings.py

before_script:
- SOLR_VERSION=$SOLR_VERSION SOLR_CORE=$SOLR_CORE bash ci/config_solr.sh
before_cache:
- rm -rf downloads/solr-${SOLR_VERSION}/

script:
  - python -m pytest --cov=winthrop

after_success:
- codecov
