language: python

python:
  - "3.5"

services:
  - mysql

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install codecov
  - cp ci/testsettings.py winthrop/local_settings.py
  - python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> winthrop/local_settings.py

script:
  - python -m pytest --cov=winthrop

after_success:
- codecov
