# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bibliographic_note', models.TextField(help_text='Full bibliographic citation')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Bibliographies',
            },
        ),
        migrations.CreateModel(
            name='Footnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet_text', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField()),
                ('is_agree', models.BooleanField()),
                ('bibliography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footnotes.Bibliography')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='bibliography',
            name='source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footnotes.SourceType'),
        ),
    ]
