# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footnotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcetype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
