# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footnotes', '0003_initial_sourcetypes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcetype',
            options={'ordering': ['name']},
        ),
    ]
