# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footnotes', '0004_sync_meta_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footnote',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
    ]
