# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 23:36
from __future__ import unicode_literals

from django.core.management import call_command
from django.contrib.auth.management import create_permissions
from django.db import migrations

def load_fixture(apps, schema_editor):
    # make sure permissions are created before loading the fixture
    # which references them
    # (when running migrations all at once, permissions may not yet exist)
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None
    call_command('loaddata', 'data-editor-group', app_label='common', verbose=0)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        ('books', '0001_initial'),
        ('people', '0001_initial'),
        ('places', '0001_initial'),
        ('footnotes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=migrations.RunPython.noop),
    ]
