# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 13:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djiffy', '0001_initial'),
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0007_set_from_to_person_for_easy_templating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('uri', models.URLField()),
                ('extra_data', jsonfield.fields.JSONField(default='{}')),
                ('text_translation', models.TextField(blank=True, verbose_name='Annotation text translation')),
                ('anchor_translation', models.TextField(blank=True, verbose_name='Anchor text translation')),
                ('quote', models.TextField(blank=True)),
                ('anchor_languages', models.ManyToManyField(related_name='_annotation_anchor_languages_+', to='books.Language')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Person')),
                ('canvas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djiffy.Canvas')),
                ('languages', models.ManyToManyField(to='books.Language')),
                ('subjects', models.ManyToManyField(to='books.Subject')),
            ],
            options={
                'abstract': False,
                'permissions': (('view_annotation', 'View annotation'), ('admin_annotation', 'Manage annotation')),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='annotation',
            name='tags',
            field=models.ManyToManyField(to='annotation.Tag'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
