# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-09 23:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djiffy', '0002_ifbook_metadata'),
        ('people', '0006_semantic_from_to_relationship_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WinAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('quote', models.TextField()),
                ('uri', models.URLField()),
                ('extra_data', jsonfield.fields.JSONField(default='{}')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='people.Person')),
                ('canvas', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='djiffy.IfPage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'permissions': (('view_annotation', 'View annotation'), ('admin_annotation', 'Manage annotation')),
            },
        ),
    ]
