# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-09 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WinAnnotation',
            new_name='Annotation',
        ),
    ]
