# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_merge_008_0010_1729'),
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('is_primary', models.BooleanField()),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Annotation')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='subjects',
            field=models.ManyToManyField(through='annotation.AnnotationSubject', to='books.Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='annotationsubject',
            unique_together=set([('annotation', 'subject')]),
        ),
    ]
