# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_initial_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='quote',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
