# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_make_annotation_quote_and_text_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='anchor_languages',
            field=models.ManyToManyField(blank=True, related_name='_annotation_anchor_languages_+', to='books.Language'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='languages',
            field=models.ManyToManyField(blank=True, to='books.Language'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='quote',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='books.Subject'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='tags',
            field=models.ManyToManyField(blank=True, to='annotation.Tag'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='text',
            field=models.TextField(),
        ),
    ]
