# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_add_annotation_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
