# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_add_flags_for_annotation_anchor_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='anchor_translation',
            field=models.TextField(blank=True, null=True, verbose_name='Anchor text translation'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='text_translation',
            field=models.TextField(blank=True, null=True, verbose_name='Annotation text translation'),
        ),
    ]
