# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_make_m2ms_optional_annotation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Annotation Type'},
        ),
        migrations.AddField(
            model_name='annotation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='quote',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='tags',
            field=models.ManyToManyField(blank=True, to='annotation.Tag'),
        ),
    ]
