# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_remove_book_is_digitized'),
        ('annotation', '0004_add_trans_fields_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='annotation',
            name='subjects',
            field=models.ManyToManyField(to='books.Subject'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='annotationlanguage',
            unique_together=set([('language', 'annotation', 'is_annotation_lang', 'is_anchor_lang')]),
        ),
        migrations.AddField(
            model_name='annotation',
            name='tags',
            field=models.ManyToManyField(to='annotation.Tag'),
        ),
    ]
