# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0005_initial_tag_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='tags',
            field=models.ManyToManyField(through='annotation.AnnotationTag', to='annotation.Tag'),
        ),
    ]
