# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_merge_008_0010_1729'),
        ('annotation', '0006_add_tags_annotations'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Annotation')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Language')),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='languages',
            field=models.ManyToManyField(through='annotation.AnnotationLanguage', to='books.Language'),
        ),
        migrations.AlterUniqueTogether(
            name='annotationlanguage',
            unique_together=set([('language', 'annotation')]),
        ),
    ]
