# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0007_create_language_annotation_many_to_many'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationlanguage',
            name='is_anchor_lang',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotationlanguage',
            name='is_annotation_lang',
            field=models.BooleanField(default=False),
        ),
    ]
