# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_merge_008_0010_1729'),
        ('annotation', '0008_add_flags_for_annotation_anchor_text'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annotationlanguage',
            unique_together=set([('language', 'annotation', 'is_annotation_lang', 'is_anchor_lang')]),
        ),
    ]
