# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0009_add_all_elements_unique_annotation_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
