# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20161229_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creatortype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='owninginstitution',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='personbookrelationshiptype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='booklanguage',
            unique_together=set([('book', 'language')]),
        ),
        migrations.AlterUniqueTogether(
            name='booksubject',
            unique_together=set([('subject', 'book')]),
        ),
    ]
