# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 21:54
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations

def load_fixture(apps, schema_editor):
    # preload NYSL owning institution for use in data import
    call_command('loaddata', 'nysl', app_label='books')

class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_initial_personbookrelationshiptypes'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=migrations.RunPython.noop),
    ]
