# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_preload_nysl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personbook',
            options={'verbose_name': 'Person/Book Interaction'},
        ),
        migrations.AlterField(
            model_name='book',
            name='is_annotated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_digitized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_extant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='original_pub_info',
            field=models.TextField(verbose_name='Original Publication Information'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place', verbose_name='Place of Publication'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='is_sammelband',
            field=models.BooleanField(default=False),
        ),
    ]
