# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djiffy', '0002_add-digital-edition'),
        ('books', '0007_title-length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='book',
            name='digital_edition',
            field=models.ForeignKey(blank=True, null=True, default=None, help_text='Digitized edition of this book, if available', on_delete=django.db.models.deletion.CASCADE, to='djiffy.Manifest'),
            preserve_default=False,
        ),
    ]
