# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_sync_meta_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_place',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='places.Place', verbose_name='Place of Publication'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='books.Publisher'),
        ),
    ]
