# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_publisher_pub_place_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Place', verbose_name='Place of Publication'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Publication Year'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Publisher'),
        ),
    ]
