# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_add-digital-edition'),
        ('books', '0010_open_up_null_blank_on_all_pub_info'),
    ]

    operations = [
    ]
