# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_merge_008_0010_on_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_digitized',
        ),
    ]
