# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_set_from_to_person_for_easy_templating'),
        ('books', '0012_plum_to_figgy'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='contributors',
            field=models.ManyToManyField(through='books.Creator', to='people.Person'),
        ),
        migrations.AlterField(
            model_name='personbook',
            name='person',
            field=models.ForeignKey(help_text='This association also determines if a person is added to the annotator autocomplete.', on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
        # add slug without unique
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
