# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_set_from_to_person_for_easy_templating'),
        ('books', '0013_generate_book_slugs'),
    ]

    operations = [
        # alter the field to enforce uniqueness
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True,
                                   help_text='Readable ID for use in URLs. Automatically generated from author, title, and year on save. Edit with *caution* because this will break permanent links.'),
        ),
    ]
