# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('geonames_id', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
